patch: move to canonical k8s (#441)
<!-- Provide a general summary of your changes in the Title above -->
<!-- markdownlint-disable MD041 -->

## 🏷️ Type of changes
<!--- What types of changes does your code introduce? -->
<!--- Put an `x` in all the boxes that apply: -->

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Documentation update
- [x] Tooling and CI
- [ ] Dependencies upgrade or change
- [ ] Chores / refactoring

## 📝 Description
<!--
Describe your changes in detail including:
  - the purpose and feature scope of this PR (what)
  - the motivation behind this change (why)
  - the impacted components (often matches conventional commit scope)
  - explanation/algorithm if required (how)
-->

This PR moves the CI ands tests to use canonical k8s
It is based on https://github.com/canonical/valkey-operator/pull/85 and
https://github.com/canonical/opensearch-single-kernel-library/pull/93
We also move the integration tests to noble


### ATTENTION

all the fixes where already merged in
https://github.com/canonical/mongo-single-kernel-library/pull/456

Fixes
https://github.com/canonical/mongo-single-kernel-library/issues/454

The main changes in the code are:
1. Catch the `ConnectionError` raise on all the container interactions
for the k8s workload, transform it into a `WorkloadServiceError` and
make sure that it is caught in the upper functions.
2. Modify the logrorate URI obtention

I proceed to show the evidence of the exception raised / failures found
during this migration:

## Connection error example

We could see `ConnectionError` raised in many places, so I added a
try-catch block around the k8s workload methods and raise a
`WorkloadServiceError`. And updated the event handlers that we missing
the catch of this exception

```
File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/events/vault.py", line 134, in _on_config_changed
    self.manager.configure_self_signed_certificates(restart=True)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/vault.py", line 195, in configure_self_signed_certificates
    self.workload.write(path, data)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/core/k8s_workload.py", line 104, in write
    self.container.push(
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/lib/python3.12/site-packages/ops/model.py", line 2833, in push
    self._pebble.push(
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/lib/python3.12/site-packages/ops/pebble.py", line 2855, in push
    response = self._request_raw('POST', '/v1/files', None, headers, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/lib/python3.12/site-packages/ops/pebble.py", line 2361, in _request_raw
    raise ConnectionError(
ops.pebble.ConnectionError: Could not connect to Pebble: socket not found at '/charm/containers/mongod/pebble.socket' (container restarted?)
unit-mongodb-k8s-0: 08:45:29 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
``` 

## Config-server failure (fixed)

We see this error when calling `mongo.add_shard(shard_name, hosts)` on
relation-joined event
```
Unit              Workload     Agent  Address      Ports  Message
config-server/0*  error        idle   10.42.0.62          hook failed: "database-peers-relation-changed"
config-server/1   active       idle   10.42.0.248         
s3-integrator/0*  active       idle   10.42.0.150         
shard-one/0*      maintenance  idle   10.42.0.148         Adding shard to config-server
shard-one/1       maintenance  idle   10.42.0.211         Adding shard to config-server
shard-two/0*      maintenance  idle   10.42.0.184         Adding shard to config-server


INFO     pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-config-server-0: 15:20:05 ERROR unit.config-server/0.juju-log database-peers:3: single_kernel_mongo.events.lifecycle:Deferring because of ServerSelectionTimeoutError config-server-0.config-server-endpoints.testing.svc.cluster.local:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms),config-server-1.config-server-endpoints.testing.svc.cluster.local:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms), Timeout: 1.0s, Topology Description: <TopologyDescription id: 6aa41c2343bcfd2224ae7212, topology_type: Unknown, servers: [<ServerDescription ('config-server-0.config-server-endpoints.testing.svc.cluster.local', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-0.config-server-endpoints.testing.svc.cluster.local:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>, <ServerDescription ('config-server-1.config-server-endpoints.testing.svc.cluster.local', 27018) server_type: Unknown, rtt: None, error=AutoReconnect('config-server-1.config-server-endpoints.testing.svc.cluster.local:27018: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 2000.0ms, connectTimeoutMS: 2000.0ms)')>]>
unit-config-server-0: 15:20:13 ERROR unit.config-server/0.juju-log database-peers:3: single_kernel_mongo.managers.sharding:shard-two shard does not have the same auth as the config server.
unit-config-server-0: 15:20:13 ERROR unit.config-server/0.juju-log database-peers:3: root:Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/sharding.py", line 402, in add_shard
    mongo.add_shard(shard_name, hosts)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/utils/mongo_connection.py", line 433, in add_shard
    self.client.admin.command("addShard", shard_url)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/database.py", line 953, in command
    return self._client._retryable_read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2076, in _retryable_read
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2038, in _retry_internal
    ).run()
      ^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 2811, in run
    res = self._read() if self._is_read else self._write()
          ^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 3043, in _read
    return self._func(self._session, self._server, conn, read_pref)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/database.py", line 941, in inner
    return self._command(
           ^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/database.py", line 778, in _command
    return conn.command(
           ^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/helpers.py", line 53, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/pool.py", line 403, in command
    return command(
           ^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/synchronous/network.py", line 212, in command
    helpers_shared._check_command_response(
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/pymongo/helpers_shared.py", line 284, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1789140013, 2), 'signature': {'hash': b'\xa1\xa80\xeb\xf8\x0fv\xa0\xeetE\xe9`B\xb5\xe0u\x90\t\x80', 'keyId': 7684297796555374616}}, 'operationTime': Timestamp(1789140013, 2)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-config-server-0/charm/src/charm.py", line 24, in <module>
    main(MongoKubernetesTestCharm)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/ops/main.py", line 39, in main
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 522, in main
    manager.run()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 506, in run
    self._emit()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/ops/_main.py", line 436, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/ops/framework.py", line 924, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/ops/framework.py", line 1034, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/events/lifecycle.py", line 262, in on_relation_joined
    self.dependent.new_peer()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/mongodb_operator.py", line 910, in new_peer
    self.update_related_hosts()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/mongodb_operator.py", line 1359, in update_related_hosts
    self.config_server_manager.add_shards()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/sharding.py", line 383, in add_shards
    self.add_shard(relation)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/sharding.py", line 408, in add_shard
    raise ShardAuthError(shard_name)
single_kernel_mongo.exceptions.ShardAuthError: shard-two
unit-config-server-0: 15:20:14 ERROR juju.worker.uniter.operation hook "database-peers-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

```
## Logrorate (fixed)

Seen in test_charm.py:

```
Unit            Workload  Agent  Address      Ports  Message
application/0*  active    idle   10.42.0.130         
mongodb-k8s/0*  waiting   idle   10.42.0.73          Mongod is not ready.
mongodb-k8s/1   waiting   idle   10.42.0.81          Mongod is not ready.
mongodb-k8s/2   waiting   idle   10.42.0.18          Waiting for primary re-election...
mongodb-k8s/3   waiting   idle   10.42.0.41          Waiting for primary re-election...
mongodb-k8s/4   waiting   idle   10.42.0.175         Waiting for primary re-election...
ubuntu@github-runner:~/actions-runner/_work/mongo-single-kernel-library/mongo-single-kernel-library$ sudo juju ssh -m testing --container mongod config-server/0 \
  /charm/bin/pebble logs -n 100 logrotate
ERROR getting unit "config-server/0": unit "config-server/0" not found
ubuntu@github-runner:~/actions-runner/_work/mongo-single-kernel-library/mongo-single-kernel-library$ sudo juju ssh -m testing --container mongod mongodb-k8s/0   /charm/bin/pebble logs -n 100 logrotate                                                                                                            
2026-09-11T15:29:51.017Z [logrotate] /usr/bin/env: 'python3': No such file or directory
2026-09-11T15:29:51.031Z [logrotate] error: access denied (try with sudo)
2026-09-11T15:29:51.764Z [logrotate] Warning: Could not access file: EACCES: permission denied, mkdir '/home/mongodb'
2026-09-11T15:29:52.639Z [logrotate] MongoServerError: Command logRotate requires authentication
2026-09-11T15:29:52.710Z [logrotate] error: error running shared postrotate script for '/var/log/mongodb/mongodb.log
2026-09-11T15:29:52.710Z [logrotate] '
2026-09-11T15:40:12.540Z [logrotate] /usr/bin/env: 'python3': No such file or directory
2026-09-11T15:40:12.547Z [logrotate] error: access denied (try with sudo)
2026-09-11T15:40:12.961Z [logrotate] Warning: Could not access file: EACCES: permission denied, mkdir '/home/mongodb'
2026-09-11T15:40:13.601Z [logrotate] MongoServerError: Command logRotate requires authentication
2026-09-11T15:40:13.659Z [logrotate] error: error running shared postrotate script for '/var/log/mongodb/audit.log
2026-09-11T15:40:13.659Z [logrotate] '
```

The log rotate URI looks like
`LOGROTATE_URI=mongodb://charmed-logrotate:AlbyBoGhaoFckSY8flaCrclYiqZRM9XR@localhost:27017/?authMechanism=SCRAM-SHA-256`
and we already pass it as env variable to the pebble layer.

The fix is to pass uri="${LOGROTATE_URI}" to the logrorate config file
and the value will be resolved at runtime

**content of /etc/logrotate.d/mongodb**
```
root@shard-one-2:/# cat /etc/logrotate.d/mongodb
/var/log/mongodb/mongodb.log
{
    rotate 25
    size 200M
    missingok
    notifempty
    create 0600 mongodb mongodb
    compress
    delaycompress
    nomail
    nocopytruncate
    sharedscripts
    postrotate
        uri="${LOGROTATE_URI}"
        /usr/bin/mongosh ${uri} --quiet --eval "db.adminCommand({logRotate: 'server'})"
    endscript
}
/var/log/mongodb/audit.log
{
    rotate 25
    size 200M
    missingok
    notifempty
    create 0600 mongodb mongodb
    compress
    delaycompress
    nomail
    nocopytruncate
    sharedscripts
    postrotate
        uri="${LOGROTATE_URI}"
        /usr/bin/mongosh ${uri} --quiet --eval "db.adminCommand({logRotate: 'audit'})"
    endscript
}
/var/log/pbm/pbm-agent.json
{
    rotate 25
    size 10M
    missingok
    notifempty
    copytruncate
    compress
    delaycompress
    nomail
```

## Rollback sharding cluster components (fixed)

Turns out that after awaiting the asyncion gather we see that we wait
for a status in the units, but the status is shown in the app:

```
App               Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
config-server     8.0.28   waiting      3  mongodb-k8s                  0  10.152.183.95   no       Waiting for shards to upgrade/downgrade to revision test/0.0.0+dirty-locally built.
continuous-write           waiting      1  continuous-write             0  10.152.183.78   no       
shard-one         8.0.28   blocked      3  mongodb-k8s       8/edge   249  10.152.183.141  no       Charm revision (249) is not up-to date with config-server (test/0.0.0+dirty-locally built).
shard-two         8.0.28   blocked      1  mongodb-k8s       8/edge   249  10.152.183.129  no       Charm revision (249) is not up-to date with config-server (test/0.0.0+dirty-locally built).

Unit                 Workload  Agent  Address      Ports  Message
config-server/0      active    idle   10.42.0.150         
config-server/1*     active    idle   10.42.0.76          
config-server/2      active    idle   10.42.0.146         Primary.
continuous-write/0*  waiting   idle   10.42.0.244         
shard-one/0*         active    idle   10.42.0.36          Primary.
shard-one/1          active    idle   10.42.0.186         
shard-one/2          active    idle   10.42.0.102         
shard-two/0*         active    idle   10.42.0.209         Primary.
``` 

## k8s status
```
ubuntu@github-runner:~/actions-runner/_work/mongo-single-kernel-library/mongo-single-kernel-library$ sudo k8s status
cluster status:           ready
control plane nodes:      10.151.33.78:6400 (voter)
high availability:        no
datastore:                etcd
network:                  enabled
dns:                      enabled at 10.152.183.108
ingress:                  disabled
load-balancer:            enabled, L2 mode
local-storage:            enabled at /var/snap/k8s/common/rawfile-storage
gateway                   enabled
```

## 🧪 Manual testing steps
<!--- Give a list of instructions to manually test your change. -->
<!--- These instructions are meant for reviewers to test the PR -->
<!--- on their development environment. -->

I have a local deployment of a sharded cluster working on canonical k8s

<img width="922" height="964" alt="image"
src="https://github.com/user-attachments/assets/7c36be9c-e0a5-42ad-a423-792f5ad4cd44"
/>

## 🔬 Automated testing steps
<!--- Describe the unit and integration tests that you added -->
<!--- to ensure that this feature works as expected. Include details -->
<!--- on the positive and negative test cases, as well as any changes
-->
<!--- made to the existing tests to ensure they are still relevant. -->

All tests continue to pass

## ✅ Checklist
<!--- Go over all the following points, and put an `x` in all the boxes
that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're
here to help! -->

- [x] My code follows the code style of this project.
- [ ] I have added or updated any relevant documentation.
- [x] I have read the [**CONTRIBUTING**](../blob/8/edge/CONTRIBUTING.md)
document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

---------

Signed-off-by: Patricia Reinoso <patricia.reinoso@canonical.com>