patch: add tenacity when reaching the snapstore to get the charmed-mongodb snap (#373)
<!-- Provide a general summary of your changes in the Title above -->
<!-- markdownlint-disable MD041 -->

## 🏷️ Type of changes
<!--- What types of changes does your code introduce? -->
<!--- Put an `x` in all the boxes that apply: -->

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Documentation update
- [ ] Tooling and CI
- [ ] Dependencies upgrade or change
- [ ] Chores / refactoring

## 📝 Description
<!--
Describe your changes in detail including:
  - the purpose and feature scope of this PR (what)
  - the motivation behind this change (why)
  - the impacted components (often matches conventional commit scope)
  - explanation/algorithm if required (how)
-->

This PR adds tenacity on a snapstore /snapd call failure. This helps
mitigate the issue but it does not work 100% of the times.

This PR changes to the snap library in charmlibs.

 https://github.com/canonical/mongo-single-kernel-library/issues/372

```
  File "/var/lib/juju/agents/unit-mongodb-4/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/mongodb_operator.py", line 184, in __init__
    self.s3_backup_manager = S3BackupManager(
                             ^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-mongodb-4/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/backups/s3.py", line 85, in __init__
    super().__init__(dependent, role, substrate, state, container)
  File "/var/lib/juju/agents/unit-mongodb-4/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/managers/backups/common.py", line 133, in __init__
    self.workload: PBMWorkload = get_pbm_workload_for_substrate(substrate)(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-mongodb-4/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/workload/backup_workload.py", line 38, in __init__
    super().__init__(role, container)
  File "/var/lib/juju/agents/unit-mongodb-4/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/core/vm_workload.py", line 47, in __init__
    self.mongod_snap = snap.SnapCache()[SNAP_NAME]
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-mongodb-4/charm/venv/lib/python3.12/site-packages/single_kernel_mongo/lib/charms/operator_libs_linux/v2/snap.py", line 1036, in __getitem__
    raise SnapNotFoundError(f"Snap '{snap_name}' not found!") from e
single_kernel_mongo.lib.charms.operator_libs_linux.v2.snap.SnapNotFoundError: Snap 'charmed-mongodb' not found!
```
## 🧪 Manual testing steps
<!--- Give a list of instructions to manually test your change. -->
<!--- These instructions are meant for reviewers to test the PR -->
<!--- on their development environment. -->

```text
deploy a replica set on VM
```

## 🔬 Automated testing steps
<!--- Describe the unit and integration tests that you added -->
<!--- to ensure that this feature works as expected. Include details -->
<!--- on the positive and negative test cases, as well as any changes
-->
<!--- made to the existing tests to ensure they are still relevant. -->

This should fix existing integration tests

## ✅ Checklist
<!--- Go over all the following points, and put an `x` in all the boxes
that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're
here to help! -->

- [ ] My code follows the code style of this project.
- [ ] I have added or updated any relevant documentation.
- [ ] I have read the [**CONTRIBUTING**](../blob/8/edge/CONTRIBUTING.md)
document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

---------

Signed-off-by: Patricia Reinoso <patricia.reinoso@canonical.com>